name: Publish to crates.io
on:
  workflow_call:
    inputs:
      plan:
        required: true
        type: string
jobs:
  publish_cargo:
    runs-on: "ubuntu-22.04"
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@stable
      - name: Publish to crates.io
        run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}